"use client"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Button, MantineProvider } from "@mantine/core"
import { NavigationSidebar } from "@/components/nav/NavigationSidebar"
import { useState } from "react"
import { SessionProvider, getSession, useSession } from "next-auth/react"
import { ApolloProvider } from "@apollo/client"
import { createApolloClient } from "@/apolloClient"
import { Session } from "inspector"
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [colorScheme, setColorScheme] = useState<"light" | "dark">("dark")
  // Toggle function
  const toggleColorScheme = () => {
    setColorScheme((prev) => (prev === "dark" ? "light" : "dark"))
  }

  return (
    <html lang="en">
      <body>
        {" "}
        <MantineProvider
          withGlobalStyles
          withNormalizeCSS
          theme={{
            /** Put your mantine theme override here */
            colorScheme,
          }}
        >
          <>
            <SessionProvider session={session}>
              <ApolloProvider client={createApolloClient()}>
                <NavigationSidebar />
                <Button onClick={toggleColorScheme}>
                  Toggle {colorScheme === "dark" ? "Light" : "Dark"} Mode
                </Button>
                {children}
              </ApolloProvider>
            </SessionProvider>
          </>
        </MantineProvider>
      </body>
    </html>
  )
}
